name: "Sonar: SonarQube Web"

on:
  pull_request:
    types: [closed]  # Trigger on closed pull requests
    paths:
      - './backend/**'
      - './frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  Sonar-Scan:
    name: SonarQube Scan for Web Application Code  
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Only run if the PR was merged
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Working Directory
        run: |
          working_dir="${{ github.event.pull_request.head.ref == 'backend' && './backend' || './frontend' }}"
         
          echo "Working Directory: $working_dir"

      # Backend Steps
      - name: Set Up Python for Backend
        if: github.event.pull_request.head.ref == 'backend'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies for Backend
        if: github.event.pull_request.head.ref == 'backend'
        run: python -m pip install -r backend/requirements.txt

      - name: Run Python Unit Tests for Backend
        if: github.event.pull_request.head.ref == 'backend'
        run: |
          echo "Running Python Unit Tests in $working_dir"
          # Uncomment the line below to actually run the tests
          # pytest backend --cov=backend --cov-report=xml

      # Frontend Steps
      - name: Set Up Node.js for Frontend
        if: github.event.pull_request.head.ref == 'frontend'
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies for Frontend
        if: github.event.pull_request.head.ref == 'frontend'
        run: npm ci

      - name: Run Angular Unit Tests with Coverage
        if: github.event.pull_request.head.ref == 'frontend'
        run: |
          echo "Running Angular Unit Tests in $working_dir"
          # Uncomment the line below to actually run the tests
          # npm run test -- --code-coverage --watch=false
