name: "Sonar: SonarQube Web"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - './backend/**'
      - './frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  Sonar-Scan:
    name: SonarQube Scan for Web Application Code  
    runs-on: ubuntu-latest
    steps:
      - name: Determine Working Directory and Sonar Token
        run: |
          working_dir="${{ github.event.pull_request.head.ref == 'backend' && './backend' || './frontend' }}"
          #sonar_token="${{ github.event.pull_request.head.ref == 'backend' && secrets.SONAR_TOKEN_BACKEND || secrets.SONAR_TOKEN_FRONTEND }}"
         
          echo "Working Directory: $working_dir"
          #echo "Sonar Token: $sonar_token"

      - name: Echo Environment
        run: |
          echo "Environment: ${{ github.ref_name }}"
