name: Test Workflow

on:
  pull_request:
    paths:
      - './backend/**'
      - './frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, World! This is a test."
