name: "Sonar: SonarQube Web"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - './backend/**'
      - './frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  Sonar-Scan:
    name: SonarQube Scan for Web Application Code  
    runs-on: ubuntu-latest
    steps:
      - name: Determine Working Directory and Sonar Token
        id: vars
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == "backend" ]]; then
            echo "Working Directory: ./backend"
            echo "Sonar Token: ${{ secrets.SONAR_TOKEN_BACKEND }}"
          elif [[ "${{ github.event.pull_request.head.ref }}" == "frontend" ]]; then
            echo "Working Directory: ./frontend"
            echo "Sonar Token: ${{ secrets.SONAR_TOKEN_FRONTEND }}"
          else
            echo "No valid working directory found."
            exit 1
          fi

      - name: Echo Environment
        run: |
          echo "Environment: ${{ github.ref_name }}"
