name: Test Workflow

on:
  push:
    paths:
      - './backend/**'
      - './frontend/**'
  pull_request:
    paths:
      - './backend/**'
      - './frontend/**'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, World! This is a test."
